MassimoDarmanin/PresentationWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PresentationWebApp.Helpers;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.Services;
using ShoppingCart.Application.ViewModels;
using ShoppingCart.Data.Repositories;
using ShoppingCart.Domain.Interfaces;
using ShoppingCart.Domain.Models;
//cart order
//item orderdetail
//https://www.youtube.com/watch?v=C2FX_37XBqM
namespace PresentationWebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;

        public OrderController(ILogger<OrderController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(Guid id)
        {
            try
            {
                string loggedInEmail = User.Identity.Name;
                return View();
            }
            catch(Exception ex)
            {
                _logger.LogError(ex.Message);
                return RedirectToAction("Error", "Home");
            }
            
        }
        /*private readonly IProductsService _productsService;
        
        public IActionResult Index()
        {
            var order = SessionHelper.GetObjectFromJson<List<OrderDetails>>(HttpContext.Session, "order");
            ViewBag.order = order;
            ViewBag.total = order.Sum(od => od.Price * od.Quantity);

            return View();
        }

        private int isExist(string id)
        {
            List<OrderDetails> order = SessionHelper.GetObjectFromJson<List<OrderDetails>>(HttpContext.Session, "order");
            for (int i = 0; i < order.Count; i++)
            {
                if (order[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }*/
        
        /*public IActionResult Buy(Guid id)
        {
            //var p = _productsService.GetProduct(id);
            if (SessionHelper.GetObjectFromJson<List<OrderDetails>>(HttpContext.Session, "order") == null)
            {
                List<OrderDetails> order = new List<OrderDetails>();
                order.Add(new OrderDetails { Product = _productsService.GetProduct(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "order", order);
            }
            else
            {
                List<OrderDetails> order = SessionHelper.GetObjectFromJson<List<OrderDetails>>(HttpContext.Session, "order");
                int index = isExist(id.ToString());
                if(index != -1)
                {
                    order[index].Quantity++;
                }
                else
                {
                    order.Add(new OrderDetails { Product = _productsService.GetProduct(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "order", order);
            }
            return RedirectToAction("Index");
        } */
    }
}

MassimoDarmanin/PresentationWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using PagedList;
using System.Web.Mvc.Html;
using Microsoft.Extensions.Logging;

namespace PresentationWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(ILogger<ProductsController> logger)
        {
            _logger = logger;
        }

        private readonly IProductsService _productsService;
        private readonly ICategoriesService _categoriesService;
        private IWebHostEnvironment _env;
        public ProductsController(IProductsService productsService, ICategoriesService categoriesService,
             IWebHostEnvironment env )
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _env = env;
        }

        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //var list = _productsService.GetProducts();

            //return View(list);

            ViewBag.CurrentSort = sortOrder;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.PriceSortParm = sortOrder == "price" ? "category" : "price";
            //ViewBag.CategorySortParm = sortOrder == "category" ? "price" : "category";
            var list = _productsService.GetProducts();

            switch (sortOrder)
            {
                case "name":
                    list = list.OrderByDescending(s => s.Name);
                    break;
                case "price":
                    list = list.OrderBy(s => s.Price);
                    break;
                case "category":
                    list = list.OrderByDescending(s => s.Category);
                    break;
                default:
                    list = list.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
            //return View(list.ToList());
        }

        //public ActionResult Index(int? i)
        //{
        //    var list = _productsService.GetProducts();
        //    return View(list.ToPagedList(i ?? 1,3));
        //}

        //public async Task<IActionResult> Index(string sortOrder,string currentFilter,
        //    string searchString,int? pageNumber)
        //{
        //    ViewData["CurrentSort"] = sortOrder;
        //    var products = from p in _productsService.GetProducts() select p;
        //    if (searchString != null)
        //    {
        //        pageNumber = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }
        //    int pageSize = 3;
        //    return View(await PaginatedList<ProductViewModel>.CreateAsync(products.AsNoTracking(), pageNumber ?? 1, pageSize));
        //}

        [HttpPost]
        public IActionResult Search(string keyword) //using a form, and the select list must have name attribute = category
        {
            var list = _productsService.GetProducts(keyword).ToList();
            _logger.LogInformation("Used Search: " + keyword);
            return View("Index", list);
        }


        public IActionResult Details(Guid id)
        {
            var p = _productsService.GetProduct(id);
            return View( p);
        }

        //the engine will load a page with empty fields
        [HttpGet]
        [Authorize (Roles ="Admin")] //is going to be accessed only by authenticated users
        public IActionResult Create()
        {
            //fetch a list of categories
            var listOfCategeories = _categoriesService.GetCategories();

            //we pass the categories to the page
            ViewBag.Categories = listOfCategeories;

            return View();
        }

        //here details input by the user will be received
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProductViewModel data, IFormFile f)
        {
            try
            {
                if(f !=  null)
                {
                    if(f.Length > 0)
                    {
                        //C:\Users\Ryan\source\repos\SWD62BEP\SWD62BEP\Solution3\PresentationWebApp\wwwroot
                        string newFilename = Guid.NewGuid() + System.IO.Path.GetExtension(f.FileName);
                        string newFilenameWithAbsolutePath = _env.WebRootPath +  @"\Images\" + newFilename;
                        
                        using (var stream = System.IO.File.Create(newFilenameWithAbsolutePath))
                        {
                            f.CopyTo(stream);
                        }

                        data.ImageUrl = @"\Images\" + newFilename;
                    }
                }

                _productsService.AddProduct(data);

                TempData["feedback"] = "Product was added successfully";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                TempData["warning"] = "Product was not added!";
            }

           var listOfCategeories = _categoriesService.GetCategories();
           ViewBag.Categories = listOfCategeories;
            return View(data);
        
        } //fiddler, burp, zap, postman

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            try
            {
                _productsService.DeleteProduct(id);
                TempData["feedback"] = "Product was deleted";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);

                TempData["warning"] = "Product was not deleted"; //Change from ViewData to TempData
            }

            return RedirectToAction("Index");
        }

        //public PartialViewResult ProductListPartial(int? page, int category)
        //{
        //    var pageNo = page ?? 1;
        //    var pageSize = 10;
        //    if(category != null)
        //    {
        //        var productList = _productsService.GetProducts(category);
        //        return PartialView(productList);
        //    }
        //    else
        //    {
        //        var productList = _productsService.GetProducts();
        //        return PartialView(productList);
        //    }
        //}
    }
}

MassimoDarmanin/PresentationWebApp/Views/Shared/DetailsPartial.cshtml
@*@model IEnumerable<ShoppingCart.Application.ViewModels.ProductViewModel>

<div>
    <h4>ProductViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
</div>

@if (User.IsInRole("Admin"))
{
    <div>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        <a asp-action="Index">Back to List</a>
    </div>
}*@

MassimoDarmanin/PresentationWebApp/Views/Shared/SearchPartial.cshtml
<form class="form-inline" method="post" action="/Products/Search">
    <div class="form-group mb-2">
        <label class="col-sm-2 col-form-label">Search:</label>
    </div>
    <div class="form-group mx-sm-3 mb-2">
        <input type="text" class="form-control" placeholder="Type your keyword here" name="keyword">
    </div>
    
    <button type="submit" class="btn btn-primary mb-2">Search</button>

    @if (User.IsInRole("Admin"))
    {
        <a href="/Products/Create" class="btn btn-link">Create Products</a>
    }
</form>

MassimoDarmanin/PresentationWebApp/Views/Shared/ViewProductsPartial.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.ProductViewModel>



@foreach (var p in Model)
{
<div class="col-6">
    <div class="card" style="width: 18rem;">
        <img src="@p.ImageUrl" class="card-img-top card-image" alt="@p.Name">
        <div class="card-body">
            <h5 class="card-title">@p.Name</h5>
            <p class="card-text">€@p.Price</p>
            <a href="/Products/Details?id=@p.Id" class="btn btn-primary">View Specifications</a>
            <a href="/Order/index?id=@p.Id" class="btn btn-outline-success">Buy</a>
            @*<a asp-controller="Order" asp-action="Buy" asp-route="@p.Id">Add to Cart</a>*@
            @if (User.IsInRole("Admin"))
            {
                <a href="/Products/Delete?id=@p.Id" class="btn btn-danger">Delete</a>}

        </div>
    </div>
</div>}

MassimoDarmanin/PresentationWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]TechShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TechShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">

            @if (TempData["feedback"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["feedback"]
                </div>
            }

            @if (TempData["warning"] != null)
            {
                <div class="alert alert-warning" role="alert">
                    @TempData["warning"]
                </div>
            }


            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            SWD6.2A Massimo Darmanin 2020-2021 
        </div>
    </footer>
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>